import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>

        <title>Instagram Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        
        <div className={`${styles.picture}`}>
          <Image src={"/images/instagram-picture.png"} alt="instagram picture" width={500} height={700} priority/>
        </div>
       <div className={`${styles.container}`}>
        <div className={`${styles.signIn}`}>
            <div className={`${styles.logo}`}>
                <Image src={"/images/instagram-logo.png"} alt="instagram logo" width={220} height={70} priority/>
            </div> 
              <form className={`${styles.form}`}>
          
                <input className={`${styles.username}`} type="text" placeholder="Phone number, username, or email"></input> <br></br>
                <input className={`${styles.password}`} type="password" placeholder='Password'></input> <br></br>
                <input className={`${styles.submit}`} type="submit" value="Log in"></input>
                <div className={`${styles.space}`}>
                <div className={`${styles.line1}`}></div>
                <div className={`${styles.or}`}>OR</div>
                <div className={`${styles.line2}`}></div>
                </div>

                <div className={`${styles.fbsection}`}>
                  
                  <div className={`${styles.fblink}`}>
                    <Image src={"/images/facebook.png"} alt="facebook" width={15} height={15} priority/>
                    <a className={`${styles.log}`} href="#">Log in with Facebook</a>
                  </div>
                  <div className={`${styles.forgot}`}>
                    <a href="#">Forgot password?</a> 
                  </div> 
                  <div className={`${styles.noAccount}`}>
                    <span className={`${styles.forgot}`}>Don't have an account? </span>
                      <span className={`${styles.sign}`}>Sign up</span>
                    
                  </div>
                </div>
              <span className={`${styles.app}`}>Get the app.</span>
              
              <div className={`${styles.appStores}`}>
                <Image className={`${styles.apple}`}  src={"/images/apple.png"} alt="apple" width={120} height={40} priority/>
                <Image className={`${styles.google}`} src={"/images/google.png"} alt="google" width={120} height={40} priority/>
              </div>

              </form> 
          </div>
        </div>

      </main>
      <Footer/>

    </>
  )
}
